ALTER TABLE public.produtos_servicos
  ADD COLUMN IF NOT EXISTS controla_estoque boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS estoque_atual numeric(12,3),
  ADD COLUMN IF NOT EXISTS estoque_minimo numeric(12,3),
  ADD COLUMN IF NOT EXISTS estoque_maximo numeric(12,3),
  ADD COLUMN IF NOT EXISTS unidade_medida text DEFAULT 'un',
  ADD COLUMN IF NOT EXISTS custo_unitario numeric(12,2),
  ADD COLUMN IF NOT EXISTS fornecedor_nome text,
  ADD COLUMN IF NOT EXISTS fornecedor_contato text,
  ADD COLUMN IF NOT EXISTS codigo_interno text,
  ADD COLUMN IF NOT EXISTS combo_items jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS combo_min_selecoes integer,
  ADD COLUMN IF NOT EXISTS combo_max_selecoes integer,
  ADD COLUMN IF NOT EXISTS promocao_ativa boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS promocao_preco numeric(12,2),
  ADD COLUMN IF NOT EXISTS promocao_inicio timestamptz,
  ADD COLUMN IF NOT EXISTS promocao_fim timestamptz,
  ADD COLUMN IF NOT EXISTS promocao_flash boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS promocao_nota text;